@startuml

class Main{
    +main(String[] args): void
}

class Pantalla {
    -buffer: Frame[]
    -grafica: Grafica
    +Pantalla()
    +mostrar(): void
    -pause(): void
}

class Grafica {
    -colaFrames: Queue<Frame>
    +Grafica()
    +generarFrames(): void
    +devolverDosFrames(): Frame[]
}

class Frame {
    -pixeles: Pixel[][]
    +Frame()
    +rellenarPixeles(): void
    +devolverPixeles(): Pixel[][]
}

class Pixel {
    -color: Color
    +Pixel()
    +devolverColor(): Color
}

class Color {
    -representacion: char
    +Color()
    +devolverRepresentacion(): char
}

Main --> Pantalla: "Llama a"
Pantalla --> Grafica: "Contiene"
Grafica--> Frame: "Tiene una cola de"
Frame --> Pixel: "Tiene una matriz de"
Pixel --> Color: "Tiene un"

@enduml