@startuml ModoEntrelazado

class Pixel {
    - char valor

    + Pixel()
    + Pixel(char valor)
    + char getValor()
    + void setValor(char nuevoValor)
}

class Frame {
    - Pixel[][] pixeles

    + Frame(int filas, int columnas)
    + void actualizarPixel(int fila, int columna, char nuevoValor)
    + boolean estaEnRango(int fila, int columna)
    + void resetear()
    + Pixel buscarPixel(int fila, int columna)
    + Pixel getPixel(int fila, int columna)
    + Pixel[][] getPixeles()
    + void mostrarFrame
}

class Nodo {
    - Frame dato
    - Nodo anterior
    - Nodo siguiente

    + Nodo(Frame dato)
    + Nodo getAnterior()
    + Nodo getSiguiente()
    + Frame geFrame()
    + void enlazarAnterior(Nodo anterior)
    + void enlazarSiguiente(Nodo siguiente)
}

class Pantalla {
    - Nodo cabeza

    + Pantalla()
    + void asignarSiguienteFrame()
    + void agregarFrame(Frame nuevoFrame)
    + Frame getFrame()
    + boolean validarNodoRepetido(Frame frame)
    + void mostrarFrame()
    + void mostrarTodosLosFrames()
    + void imprimirPantalla()


}

Pixel *-- Frame : recibe
Frame *-- Nodo : envuelve
Nodo *-- Pantalla : Lista de

@enduml