@startuml
class Pantalla {
    - dato: nodo
    - cabeza: nodo
    + printFrame(): void
    + asigneNextFrame(): frame
    + verifyBuffer(): void
    + printIndividualFrame():void
    + getFrames(): frame
}

class Nodo {
    - dato: frame
    - siguiente: nodo
    - anterior: nodo
    + getNodo()
}

class Frame {
    - pixel: pixel[][]
    + getPixel():pixels
    + reset():void
    + setPixel():pixel
    + findPixel():pixel
}

class Pixel {
    - char: asterisco
    - char: punto
    - char: más
    + getAsterisco():char
    + getPunto():char
    + getMas():char
}

Pantalla --> Nodo
Nodo --> Frame
Frame --> Pixel
@enduml