@startuml

class Pixel{
    - valor
    + get
    + set
}

class Frame{
    - pixel
    + add
    + update
    + delete
}

class Screen{
    - frame
    + combine
    + choose 
    + print
}

class Main{
    + start
}

Pixel -- Frame
Frame -- Screen
Screen -- Main

@enduml