@startuml

class Coordinate{
    -x:int
    -y:int
    +Coordinate(x:int,y:int)
    +getX:int
    +getY:int
    +setX(x:int)
    +setY(y:int)
}

class Pixel{
    -value:int
    +Pixel(value:int)
    +getValue:int
    +setValue(value:int)
    +translate(value:int)
}

class Frame{
    -pixeles:Pixel[][]
    -width:int
    -height:int
    +Frame(width:int,height:int)
    +updatePixel(pixeles:Pixel[][])
    +deletePixel(pixeles:Pixel[][])
    +setPixel(x:int,y:int,value:int)
    +getHeight:int
    +getWidth:int
    +printFrame()  
}

class Screen{
    -frame1:Frame
    -frame2:Frame
    +Screen(frame1:Frame,frame2:Frame)
    +combine()
    +print()
}

Screen --> Frame
Frame --> Pixel
Pixel --> Coordinate
@enduml
