@startuml
skinparam classAttributeIconSize 0

class Pixel {
    - value: char
    - WIDTH: int
    - HEIGHT: int
    + getValue(): char
    + setValue(value: char)
    + generateFrame(offset: int): char[][]
    + combineFrames(frame1: char[][], frame2: char[][]): char[][]
    + printFrame(frame: char[][])
    + main(args: String[])
}

class Frame {
    - pixels: Pixel[][]
    - x: int
    - y: int
    + getPixel(x, y)
    + setPixel(x, y, pixel: Pixel)
}

class DataBase {
    - frames: Frame[]
    - activeFrame: Frame
    + addFrame(frame: Frame)
    + switchFrame(index: int)
    + getActiveFrame(): Frame
}

class Display {
    - displayPixels: Pixel[][]
    + render()
    + updateDataBase(db: DataBase)
}

Display --> DataBase : usa
DataBase --> Frame : contiene
Frame --> Pixel : contiene

@enduml