@startuml
class Pantalla {
  -String class
  -GetFrame()
}

class Buffer {
  -mostrarFrameEscogido(Frame1, Frame2, ResultadoCombinado)
}

class Pixel {
  -char[][] 
  ListaElementos()
}

class Frame1 {
  -char[][]
  PosicionFrame(Pixel)
}

class Frame2 {
  -char[][]
  PosicionFrame(Pixel)
}

class ResultadoCombinado {
  -char[][]
  combinar(Frame1, Frame2)
}

Pantalla --> Buffer
Buffer --> Frame1
Buffer --> Frame2
Buffer --> ResultadoCombinado
Pixel --> Frame1
Pixel --> Frame2
@enduml